config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :customers
  root 'customers#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  has_many :customers
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  def full_name(sama)
    full_name = family_name + given_name + sama
    return full_name
  end
  validates :family_name, presence: true, length: { maximum: 20 }
  validates :given_name,  presence: true, length: { maximum: 20 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email,       presence: true, format: { with: VALID_EMAIL_REGEX }
  belongs_to :company
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  # before_action :authenticate_user!
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]


  def index
    @customers = Customer.page(params[:page])
  end

  def new
    @customer = Customer.new
  end

  def create
    @customer = Customer.new(customer_params)
    if @customer.save
      redirect_to @customer
    else
      render :new
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to @customer
    else
      render :edit
    end
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    redirect_to customers_url
  end

  private

  def customer_params
    params.require(:customer).permit(
      :family_name,
      :given_name,
      :email
      )
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_form.html.erb
  <%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div class="alert alert-danger">
      <p><b><%= @customer.errors.count %>件のエラーがあります</b></p>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :family_name %><br>
    <%= f.text_field :family_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :given_name %><br>
    <%= f.text_field :given_name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :email %><br>
    <%= f.text_field :email, class: "form-control" %>
  </div>
  <%= f.submit %>
<% end %>

app/views/customers/edit.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客情報の編集</h1>
    <%= render 'form' %>
    <button type="button" class="btn btn-default btn-sm" data-toggle="modal" data-target="#delete-customer">顧客情報を削除する</button>
  </div>
</div>

<!-- 下記のモーダルは通常は隠れているので、どこに書いてもＯＫ -->
<div class="modal fade" id="delete-customer">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">顧客情報の削除</h4>
      </div>
      <div class="modal-body">
        <p><%= @customer.family_name %>さんを削除しますか？</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">キャンセル</button>
        <%= link_to '削除する', @customer, method: :delete, class: "btn btn-danger" %>
      </div>
    </div>
  </div>
</div>

app/views/customers/index.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1>顧客情報一覧</h1>
    <p><%= link_to '新規登録', new_customer_path, class:"btn btn-primary " %></p>

    <p>お客様情報が表示されます。</p>
    <table class="table table-striped">
      <thead>
        <th>姓</th>
        <th>名</th>
        <th>電子メール</th>
        <th>リンク</th>
      </thead>
      <tbody>
        <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.family_name %></td>
            <td><%= customer.given_name %></td>
            <td><%= customer.email %></td>
            <td><%= link_to '詳細', customer, class: "btn btn-default btn-xs" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= paginate @customers %>
  </div>
</div>

app/views/customers/new.html.erb
<h1>Customers#new</h1>
<p>Find me in app/views/customers/new.html.erb</p>



<div class="row">
  <div class="col-lg-12">
    <h1>顧客新規登録</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/customers/show.html.erb
<!--
<h1>Customers#show</h1>
<p>Find me in app/views/customers/show.html.erb</p>
 -->

<div class="row">
  <div class="col-lg-12">
    <h1>顧客詳細</h1>
    <dl>
      <dt>お名前</dt>
      <dd><%= @customer.full_name("様") %></dd>
      <dt>電子メール</dt>
      <dd><%= @customer.email %></dd>
    </dl>
  </div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-menu">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/customers">顧客管理システム</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">ダミー</a></li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
      <div class="collapse navbar-collapse" id="navbar-collapse-menu">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "設定変更", edit_user_registration_path %></li>
          <li><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "新規登録", new_user_registration_path %></li>
          <li><%= link_to "ログイン", new_user_session_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ElitesCrm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" integrity="sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css" integrity="sha384-aUGj/X2zp5rLCbBxumKTCw2Z50WgIr1vs/PFN4praOTvYXWlVyh2UtNUU0KAUhAX" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js" integrity="sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==" crossorigin="anonymous"></script>
</head>
<body>

<%= render 'layouts/header' %>

<div class="container">
  <% if notice.present? %>
    <div class="alert alert-dismissable alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= notice %></p>
    </div>
  <% end %>

  <% if alert.present? %>
    <div class="alert alert-dismissable alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <p><%= alert %></p>
    </div>
  <% end %>

  <%= yield %>
</div>



</body>
</html>